version: '3.4'

services:

   api:
     build:
       context: ./
       args:
         - application=dynamodb-go-sample
         - friendly=Sample API
         - description=Sample API using dynamodb as a backing store
         - build_hash=${BUILD_HASH:-localbuild_hashmissing}
         - build_user=${BUILD_USER:-unknown}
         - build_branch=${BUILD_BRANCH:-nobranch}
         - build_number=${BUILD_NUMBER:-1.0.0}
         - build_group=${BUILD_GROUP:-nogroupspecified}
         - build_date=${BUILD_DATE}
         - repo_url=${REPO_URL}
         - vendor=${VENDOR:-Chad Grant}
         - builder_img=${REGISTRY}/chadgrant/base:golang-1.13.5-alpine
         - runtime_img=${REGISTRY}/chadgrant/base:alpine-3.11.2
     image: ${REGISTRY}/chadgrant/dynamodb-go-sample:${BUILD_NUMBER:-1.0.0}
     container_name: sample_api
     restart: unless-stopped
     ports:
       - 5000:8080
     healthcheck:
        test: "curl -f http://localhost:8080/health/liveness || exit 1"
        interval: 30s
        timeout: 2s
        retries: 3
        start_period: 5s
     environment:
        DYNAMO_ENDPOINT: "http://data:8000"       
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: key
        AWS_SECRET_ACCESS_KEY: secret
        
   tests:
      build:
       context: ./
       dockerfile: Dockerfile.tests
       args:
        - runtime_img=${REGISTRY}/chadgrant/golang-testing:1.13.5-alpine
      image: ${REGISTRY}/chadgrant/dynamodb-go-sample-test:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_test
      depends_on:
        - data
        - api
      environment:
        DYNAMO_ENDPOINT: "http://data:8000"
        TEST_INTEGRATION: 1

   ui:
      build:
        args:
          - ui=typescript-react
        context: ./ui
      image: ${REGISTRY}/chadgrant/dynamodb-go-sample-ui:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_ui
      restart: unless-stopped
      ports:
       - 4000:80
      environment:
        API_ENDPOINT: "http://localhost:5000"

   data:
      build:
       context: ./db
      image: ${REGISTRY}/chadgrant/dynamodb-go-sample-data:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_data
      restart: unless-stopped
      ports:
         - 8000:8000