version: '3.4'

volumes:
  prometheus_data: {}
  grafana_data: {}

x-default-service: &svc
  build:
    args: &args
      VENDOR: ${VENDOR:-chadgrant}
      GROUP: ${GROUP:-nogroupspecified}    
      SERVICE: ${SERVICE:-dynamodb-go-sample}
      SERVICE_FRIENDLY: ${SERVICE_FRIENDLY:-Sample API}
      SERVICE_DESCRIPTION: ${SERVICE_DESCRIPTION:-Sample API using dynamodb as a backing store}
      SERVICE_URL: ${SERICE_URL:-http://localhost:8080}
      BUILD_HASH: ${BUILD_HASH:-localbuild_hashmissing}
      BUILD_USER: ${BUILD_USER:-unknown}
      BUILD_BRANCH: ${BUILD_BRANCH:-nobranch}
      BUILD_NUMBER: ${BUILD_NUMBER:-1.0.0}
      BUILD_DATE: ${BUILD_DATE}
      BUILD_REPO: ${BUILD_REPO}

services:

  api:
    <<: *svc
    build:
      context: ./
      args:
        <<: *args
    image: ${DOCKER_REGISTRY:-docker.io}/${VENDOR:-chadgrant}/${DOCKER_IMAGE:-dynamodb-go-sample}:${BUILD_NUMBER:-1.0.0}
    container_name: sample_api
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:8080/live || exit 1"
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 5s    
    ports:
      - 5000:8080
    environment:
      DYNAMO_ENDPOINT: "http://data:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: secret
      PROMETHEUS_PUSH_ENABLED: "true"
      PROMETHEUS_PUSH_HOST: "http://prometheus_gateway:9091"
      
  tests:
    <<: *svc
    build:
      context: .
      dockerfile: tests/Dockerfile
      args:
        <<: *args
    image: ${DOCKER_REGISTRY:-docker.io}/${VENDOR:-chadgrant}/${DOCKER_IMAGE:-dynamodb-go-sample}-test:${BUILD_NUMBER:-1.0.0}
    container_name: sample_api_test
    depends_on:
      - data
      - api
    environment:
      DYNAMO_ENDPOINT: "http://data:8000"
      TEST_INTEGRATION: 1
      API_ENDPOINT: "http://api:8080"

  ui:
    build:
      args:
        UI: typescript-react
      context: ./ui
    image: ${DOCKER_REGISTRY:-docker.io}/${VENDOR:-chadgrant}/${DOCKER_IMAGE:-dynamodb-go-sample}-ui:${BUILD_NUMBER:-1.0.0}
    container_name: sample_api_ui
    restart: unless-stopped
    ports:
      - 4000:80
    environment:
      API_ENDPOINT: "http://localhost:5000"

  data:
    build:
      context: ./db
    image: ${DOCKER_REGISTRY:-docker.io}/chadgrant/dynamodb-go-sample-db:${BUILD_NUMBER:-1.0.0}
    container_name: sample_api_data
    restart: unless-stopped
    ports:
      - 8000-8001:8000-8001

  grafana:
    image: grafana/grafana:6.6.2
    container_name: sample_api_grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password

  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: sample_api_prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - prometheus_gateway
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus:/etc/prometheus

  prometheus_gateway:
    image: prom/pushgateway:v1.1.0
    container_name: sample_api_prometheus_gateway
    restart: unless-stopped
    ports:
      - 9091:9091