ARG runtime_img="golang:1.13.5"

FROM $runtime_img

WORKDIR /go/src/github.com/chadgrant/dynamodb-go-sample

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile main.go ./ 
COPY store ./store/

CMD ["go","test","-v","./..."]