FROM golang:1.13

ARG application

WORKDIR /go/src/github.com/chadgrant/$application

COPY main.go /go/src/github.com/chadgrant/$application
COPY store /go/src/github.com/chadgrant/$application/store/
COPY data /go/src/github.com/chadgrant/$application/data/

RUN go get ./...

CMD ["go","test","-v","./..."]