version: '3.4'

services:

   api:
     build:
       context: ./
       args:
         - application=dynamodb-go-sample
         - friendly=Sample API
         - build_hash=${BUILD_HASH:-localbuild_hashmissing}
         - build_user=${BUILD_USER:-unknown}
         - build_branch=${BUILD_BRANCH:-nobranch}
         - build_number=${BUILD_NUMBER:-1.0.0}
         - build_group=${BUILD_GROUP:-nogroupspecified}
     image: chadgrant/sample_api:${BUILD_NUMBER:-1.0.0}
     container_name: sample_api
     restart: unless-stopped
     ports:
       - 5000:8080
     environment:
        DYNAMO_ENDPOINT: "http://data:8000"       
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: key
        AWS_SECRET_ACCESS_KEY: secret
        
   tests:
      build:
       context: ./
       dockerfile: Dockerfile.tests
      image: chadgrant/sample_api_test:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_test
      depends_on:
        - data
        - api
      environment:
        DYNAMO_ENDPOINT: "http://data:8000"
        TEST_INTEGRATION: 1

   ui:
      build:
        context: ./ui
      image: chadgrant/sample_api_ui:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_ui
      restart: unless-stopped
      ports:
       - 3000:80
      environment:
        API_ENDPOINT: "http://localhost:5000"

   data:
      build:
       context: ./db
      image: chadgrant/sample_api_data:${BUILD_NUMBER:-1.0.0}
      container_name: sample_api_data
      restart: unless-stopped
      ports:
         - 8000:8000