global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'dynamodb_go_sample'
    static_configs:
      - targets: [
      'api:5000',
      'prometheus_gateway:9091'
      ]