name: Docker Image CI

on: [push]

jobs:  
  test-docker:
    name: Build & Test Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker images
      run: make docker-build
    - name: Test Docker Images
      run: make docker-test
